# Generated by Django 2.2.15 on 2020-08-28 10:10

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HowtoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('creation_order', '作成された順'), ('due_order', '締め切り順')], default='creation_order', max_length=50, verbose_name='並び順')),
                ('ascending_or_descending', models.CharField(choices=[('ascending', '昇順'), ('descending', '降順')], default='descending', max_length=50, verbose_name='昇順か降順か')),
            ],
            options={
                'db_table': 'how_to_order',
            },
        ),
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('memo', models.TextField(blank=True, default='詳細なし', null=True, verbose_name='詳細')),
                ('priority', models.CharField(choices=[('danger', '高い'), ('warning', '普通'), ('primary', '低い')], default='warning', max_length=50, verbose_name='優先度')),
                ('duedate', models.DateField(default=django.utils.timezone.now, verbose_name='締め切り日')),
                ('status', models.CharField(choices=[('doing', '未完了'), ('done', '完了')], default='doing', max_length=50, verbose_name='状況')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
    ]
