# Generated by Django 2.2.15 on 2020-09-13 08:29

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='HowtoOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.CharField(choices=[('creation_order', '作成された順'), ('due_order', '締め切り順'), ('priority_order', '優先度順')], default='creation_order', max_length=50, verbose_name='並び順')),
                ('ascending_or_descending', models.CharField(choices=[('ascending', '昇順'), ('descending', '降順')], default='ascending', max_length=50, verbose_name='昇順か降順か')),
                ('user_name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'how_to_order',
            },
        ),
        migrations.CreateModel(
            name='ToDoModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('memo', models.TextField(blank=True, default='詳細なし', null=True, verbose_name='詳細')),
                ('priority', models.CharField(choices=[('danger', '高い'), ('warning', '普通'), ('primary', '低い')], default='warning', max_length=50, verbose_name='優先度')),
                ('duedate', models.DateField(default=django.utils.timezone.now, verbose_name='締め切り日')),
                ('status', models.CharField(choices=[('doing', '未完了'), ('done', '完了')], default='doing', max_length=50, verbose_name='状況')),
                ('user_name', models.CharField(max_length=200, verbose_name='ユーザー名')),
            ],
            options={
                'db_table': 'todo',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('order', models.CharField(choices=[('creation_order', '作成された順'), ('due_order', '締め切り順'), ('priority_order', '優先度順')], default='creation_order', max_length=50, verbose_name='並び順')),
                ('ascending_or_descending', models.CharField(choices=[('ascending', '昇順'), ('descending', '降順')], default='ascending', max_length=50, verbose_name='昇順か降順か')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'custom_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
