# Generated by Django 2.2.15 on 2020-09-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_howtoorder_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='howtoorder',
            name='ascending_or_descending',
            field=models.CharField(choices=[('ascending', '昇順'), ('descending', '降順')], default='ascending', max_length=50, verbose_name='昇順か降順か'),
        ),
    ]
